### ISSUE TITLE
Create the use case diagram based on the initial requirements

### ISSUE THREAD

**Issue by Perilous612** [Nightmareviper/ICT2201_P6-1#12]
Create a use case diagram from the initial requirement with some of our own assumptions.
- [x] @IUshiii Done with the use case diagram
- [ ] @Perilous612 Approved the use case diagram

**Comment by IUshiii** [comment]
This is the use case diagram based on the initial requirements. @Perilous612 please do review it.


![Image](https://user-images.githubusercontent.com/94039886/189846143-3ba01b36-1101-4881-8418-b1f42c214dc4.png)

**Comment by Perilous612** [comment]
Great job !!! we can start with the Figma with this use case for now
